### ISSUE TITLE
Constructing certificates with a Buffer bypasses PEM parsing

### ISSUE THREAD

**Issue by chalford** [PeculiarVentures/x509#18]
Stack trace:
```
Error: Constructed encoding used for primitive type
    at Function.parse (/Users/xyz/repos/project/node_modules/@peculiar/asn1-schema/build/cjs/parser.js:27:19)
    at Function.parse (/Users/xyz/repos/project/node_modules/@peculiar/asn1-schema/build/cjs/convert.js:13:35)
    at new AsnData (/Users/xyz/repos/project/node_modules/@peculiar/x509/build/x509.cjs.js:73:47)
    at new PemData (/Users/xyz/repos/project/node_modules/@peculiar/x509/build/x509.cjs.js:277:13)
    at new X509Certificate (/Users/xyz/repos/project/node_modules/@peculiar/x509/build/x509.cjs.js:588:13)
```

Expected result: When I construct a new X509Certificate with a Buffer containing a PEM file, I get back an X509Certificate object
Actual result: Execution fails with the above stack trace.

I think I've tracked this down to a call to `toArrayBuffer` in PemData (https://github.com/PeculiarVentures/x509/blob/master/src/pem_data.ts#L20), where the input is checked to see if it is a string. Only strings then get checked to see if they are a PEM file.

The workaround is to call `.toString()` on the Buffer before constructing an X509Certificate object.

**Comment by microshine** [comment]
@chalford I've published `@oeculiar/x509@1.6.1`. It fixes the current issue.

Please try it
