### ISSUE TITLE
tsyringe requires a reflect polyfill.

### ISSUE THREAD

**Issue by HaimenToshi** [PeculiarVentures/x509#57]
Hello. I've been using this library on Bun for around 6 months without a single issue, however last night I did an upgrade to Bun's binary and my app stopped launching. Error : 

`1 | if (typeof Reflect === "undefined" || !Reflect.getMetadata) {
2 |     throw new Error("tsyringe requires a reflect polyfill. Please add 'import \"reflect-metadata\"' to the top of your entry point.");
              ^
error: tsyringe requires a reflect polyfill. Please add 'import "reflect-metadata"' to the top of your entry point.
      at /srv/bun/iSAIM/node_modules/tsyringe/dist/esm5/index.js:2:10
      at /srv/bun/iSAIM/node_modules/@peculiar/x509/build/x509.es.js:36:0
      at /srv/bun/iSAIM/src/server.js:5:0`

Following the error's message suggestion of adding import reflect-metadata to the top of my script doesn't work. Any idea what is wrong? Thanks.

**Comment by HaimenToshi** [comment]
Closed as not related to this package but rather bun.sh
